include:
  - docker-compose.deps.yml

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dealership
      SPRING_DATA_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_MAIL_HOST: mailhog
      JAVA_TOOL_OPTIONS: -Duser.timezone=UTC
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
